export const SESION_EXITOSA = 'SESION_EXITOSA';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const SESION_ERROR = 'SESION_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_PERSONAS = 'OBTENER_PERSONAS';
export const OBTENER_PERSONA = 'OBTENER_PERSONA';
export const AGREGAR_PERSONA = 'AGREGAR_PERSONA';
export const EDITAR_PERSONA = 'EDITAR_PERSONA';
export const ELIMINAR_PERSONA = 'ELIMINAR_PERSONA';
export const QUITAR_PERSONA = 'QUITAR_PERSONA';
export const QUITAR_PERSONAS = 'QUITAR_PERSONAS';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const MOSTRAR_ERROR = 'MOSTRAR_ERROR';
export const OCULTAR_ERROR = 'OCULTAR_ERROR';